apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-models-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: employee-salary.localhost
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: employee-salary-prediction
              port:
                number: 80

